"""initial schema

Revision ID: d2e904078dd5
Revises: 
Create Date: 2026-09-03 19:24:54.010115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2e904078dd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('precision', sa.String(length=16), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('hydrant',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hydrant_latitude'), 'hydrant', ['latitude'], unique=False)
    op.create_index(op.f('ix_hydrant_longitude'), 'hydrant', ['longitude'], unique=False)
    op.create_table('incident',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_number', sa.String(length=64), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_type', sa.String(length=128), nullable=False),
    sa.Column('call_subtype', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('cross_street', sa.Text(), nullable=True),
    sa.Column('municipality', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geo_source', sa.String(length=16), nullable=True),
    sa.Column('station_area', sa.Integer(), nullable=True),
    sa.Column('battalion', sa.Integer(), nullable=True),
    sa.Column('talkgroup', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('alarm_level', sa.String(length=32), nullable=True),
    sa.Column('raw_source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_area_dispatched', 'incident', ['station_area', 'dispatched_at'], unique=False)
    op.create_index('ix_incident_category_dispatched', 'incident', ['category', 'dispatched_at'], unique=False)
    op.create_index(op.f('ix_incident_dispatched_at'), 'incident', ['dispatched_at'], unique=False)
    op.create_index('ix_incident_municipality', 'incident', ['municipality'], unique=False)
    op.create_index('ix_incident_status_dispatched', 'incident', ['status', 'dispatched_at'], unique=False)
    op.create_table('source_poll',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('received', sa.Integer(), nullable=True),
    sa.Column('parsed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_poll_at'), 'source_poll', ['at'], unique=False)
    op.create_table('incident_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_incident_at', 'incident_event', ['incident_id', 'at'], unique=False)
    op.create_table('unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('station', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'unit', name='uq_unit_incident')
    )
    op.create_index(op.f('ix_unit_incident_id'), 'unit', ['incident_id'], unique=False)
    op.create_index(op.f('ix_unit_station'), 'unit', ['station'], unique=False)
    op.create_index(op.f('ix_unit_unit'), 'unit', ['unit'], unique=False)
    op.drop_table('_prisma_migrations')
    op.drop_index(op.f('SourcePoll_at_idx'), table_name='SourcePoll')
    op.drop_table('SourcePoll')
    op.drop_index(op.f('Unit_incidentId_unit_key'), table_name='Unit')
    op.drop_index(op.f('Unit_station_idx'), table_name='Unit')
    op.drop_index(op.f('Unit_unit_idx'), table_name='Unit')
    op.drop_table('Unit')
    op.drop_index(op.f('IncidentEvent_incidentId_at_idx'), table_name='IncidentEvent')
    op.drop_table('IncidentEvent')
    op.drop_table('GeocodeCache')
    op.drop_index(op.f('Incident_category_dispatchedAt_idx'), table_name='Incident')
    op.drop_index(op.f('Incident_dispatchedAt_idx'), table_name='Incident')
    op.drop_index(op.f('Incident_municipality_idx'), table_name='Incident')
    op.drop_index(op.f('Incident_stationArea_dispatchedAt_idx'), table_name='Incident')
    op.drop_index(op.f('Incident_status_dispatchedAt_idx'), table_name='Incident')
    op.drop_table('Incident')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Incident',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('incidentNumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dispatchedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('closedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('callType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('callSubtype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crossStreet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('municipality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('geoSource', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stationArea', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('battalion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('talkgroup', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alarmLevel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rawSource', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rawPayload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('firstSeenAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('lastSeenAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Incident_pkey'))
    )
    op.create_index(op.f('Incident_status_dispatchedAt_idx'), 'Incident', ['status', 'dispatchedAt'], unique=False)
    op.create_index(op.f('Incident_stationArea_dispatchedAt_idx'), 'Incident', ['stationArea', 'dispatchedAt'], unique=False)
    op.create_index(op.f('Incident_municipality_idx'), 'Incident', ['municipality'], unique=False)
    op.create_index(op.f('Incident_dispatchedAt_idx'), 'Incident', ['dispatchedAt'], unique=False)
    op.create_index(op.f('Incident_category_dispatchedAt_idx'), 'Incident', ['category', 'dispatchedAt'], unique=False)
    op.create_table('GeocodeCache',
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolvedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('address', name=op.f('GeocodeCache_pkey'))
    )
    op.create_table('IncidentEvent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incidentId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incidentId'], ['Incident.id'], name=op.f('IncidentEvent_incidentId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('IncidentEvent_pkey'))
    )
    op.create_index(op.f('IncidentEvent_incidentId_at_idx'), 'IncidentEvent', ['incidentId', 'at'], unique=False)
    op.create_table('Unit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incidentId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('station', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dispatchedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incidentId'], ['Incident.id'], name=op.f('Unit_incidentId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Unit_pkey'))
    )
    op.create_index(op.f('Unit_unit_idx'), 'Unit', ['unit'], unique=False)
    op.create_index(op.f('Unit_station_idx'), 'Unit', ['station'], unique=False)
    op.create_index(op.f('Unit_incidentId_unit_key'), 'Unit', ['incidentId', 'unit'], unique=True)
    op.create_table('SourcePoll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('adapter', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ok', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('latencyMs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('received', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parsed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('SourcePoll_pkey'))
    )
    op.create_index(op.f('SourcePoll_at_idx'), 'SourcePoll', ['at'], unique=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.drop_index(op.f('ix_unit_unit'), table_name='unit')
    op.drop_index(op.f('ix_unit_station'), table_name='unit')
    op.drop_index(op.f('ix_unit_incident_id'), table_name='unit')
    op.drop_table('unit')
    op.drop_index('ix_event_incident_at', table_name='incident_event')
    op.drop_table('incident_event')
    op.drop_index(op.f('ix_source_poll_at'), table_name='source_poll')
    op.drop_table('source_poll')
    op.drop_index('ix_incident_status_dispatched', table_name='incident')
    op.drop_index('ix_incident_municipality', table_name='incident')
    op.drop_index(op.f('ix_incident_dispatched_at'), table_name='incident')
    op.drop_index('ix_incident_category_dispatched', table_name='incident')
    op.drop_index('ix_incident_area_dispatched', table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_hydrant_longitude'), table_name='hydrant')
    op.drop_index(op.f('ix_hydrant_latitude'), table_name='hydrant')
    op.drop_table('hydrant')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
